export { NativeClient, NativeServiceError, type NativeClientOptions } from './client.js'
export {
  PROTOCOL_VERSION,
  baselineCaptureResultSchema,
  displayApplyRequestSchema,
  displayApplyResultSchema,
  displayIdSchema,
  displayRequestSchema,
  displayRestoreResultSchema,
  displaySettingsSchema,
  displayStateSchema,
  gammaRampSchema,
  restoreAllResultSchema,
  serviceBaselinesRestoredDataSchema,
  windowsDisplayStateSchema,
  amdDisplayStateSchema,
  foregroundApplicationChangedDataSchema,
  displayTopologyChangedDataSchema,
  foregroundApplicationSchema,
  foregroundCurrentResultSchema,
  foregroundApplicationsResultSchema,
  displayAdapterSchema,
  displayListResultSchema,
  displaySchema,
  capabilitySchema,
  displayCapabilitiesSchema,
  displayCapabilitiesResultSchema,
  displayTopologyRefreshResultSchema,
  providerControlStateSchema,
  nativeDisplayStateSchema,
  nativeEventSchema,
  nativeMessageSchema,
  nativeRequestSchema,
  nativeResponseSchema,
  systemInfoSchema,
  serviceHealthSchema,
  heartbeatResultSchema,
  type NativeEvent,
  type NativeRequest,
  type NativeResponse,
  type SystemInfo,
  type ServiceHealth,
  type HeartbeatResult,
  type ForegroundApplication,
  type Display,
  type Capability,
  type DisplayCapabilities,
  type DisplayCapabilityReport,
  type DisplayTopologyRefreshResult,
  type DisplaySettings,
  type GammaRamp,
  type DisplayState,
  type BaselineCaptureResult,
  type DisplayApplyResult,
  type DisplayRestoreResult,
  type RestoreAllResult
} from './protocol.js'
