export { NativeClient, type NativeClientOptions } from './client.js'
export {
  PROTOCOL_VERSION,
  foregroundApplicationChangedDataSchema,
  foregroundApplicationSchema,
  foregroundCurrentResultSchema,
  displayAdapterSchema,
  displayListResultSchema,
  displaySchema,
  capabilitySchema,
  displayCapabilitiesSchema,
  displayCapabilitiesResultSchema,
  providerControlStateSchema,
  nativeDisplayStateSchema,
  nativeEventSchema,
  nativeMessageSchema,
  nativeRequestSchema,
  nativeResponseSchema,
  systemInfoSchema,
  type NativeEvent,
  type NativeRequest,
  type NativeResponse,
  type SystemInfo,
  type ForegroundApplication,
  type Display,
  type Capability,
  type DisplayCapabilities,
  type DisplayCapabilityReport
} from './protocol.js'
