export {
  NativeClient,
  NativeServiceError,
  type NativeClientOptions
} from './client.js'
export {
  PROTOCOL_VERSION,
  baselineCaptureResultSchema,
  displayApplyRequestSchema,
  displayApplyResultSchema,
  displayIdSchema,
  displayRequestSchema,
  displayRestoreResultSchema,
  displaySettingsSchema,
  displayStateSchema,
  gammaRampSchema,
  restoreAllResultSchema,
  windowsDisplayStateSchema,
  amdDisplayStateSchema,
  foregroundApplicationChangedDataSchema,
  foregroundApplicationSchema,
  foregroundCurrentResultSchema,
  foregroundApplicationsResultSchema,
  displayAdapterSchema,
  displayListResultSchema,
  displaySchema,
  capabilitySchema,
  displayCapabilitiesSchema,
  displayCapabilitiesResultSchema,
  providerControlStateSchema,
  nativeDisplayStateSchema,
  nativeEventSchema,
  nativeMessageSchema,
  nativeRequestSchema,
  nativeResponseSchema,
  systemInfoSchema,
  type NativeEvent,
  type NativeRequest,
  type NativeResponse,
  type SystemInfo,
  type ForegroundApplication,
  type Display,
  type Capability,
  type DisplayCapabilities,
  type DisplayCapabilityReport,
  type DisplaySettings,
  type GammaRamp,
  type DisplayState,
  type BaselineCaptureResult,
  type DisplayApplyResult,
  type DisplayRestoreResult,
  type RestoreAllResult
} from './protocol.js'
