<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>ChromaShift.DisplayService</AssemblyName>
    <RootNamespace>ChromaShift.DisplayService</RootNamespace>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>partial</TrimMode>
    <EnableCompressionInSingleFile>false</EnableCompressionInSingleFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Win32.SystemEvents" Version="10.0.10" />
    <PackageReference Include="Varun.NvAPIWrapper.Net" Version="9.0.3" />
    <_ILLinkSuppressions Include="$(MSBuildProjectDirectory)\ILLink.LinkAttributes.xml"
                         Condition="'$(PublishTrimmed)' == 'true'" />
    <TrimmerRootAssembly Include="NvAPIWrapper" Condition="'$(PublishTrimmed)' == 'true'" />
  </ItemGroup>
  <ItemGroup>
    <None Include="ThirdPartyNotices\THIRD-PARTY-NOTICES.txt"
          Link="THIRD-PARTY-NOTICES.txt"
          CopyToPublishDirectory="PreserveNewest"
          ExcludeFromSingleFile="true" />
    <None Include="ThirdPartyNotices\licenses\GPL-3.0.txt"
          Link="licenses\GPL-3.0.txt"
          CopyToPublishDirectory="PreserveNewest"
          ExcludeFromSingleFile="true" />
    <None Include="ThirdPartyNotices\licenses\LGPL-3.0.txt"
          Link="licenses\LGPL-3.0.txt"
          CopyToPublishDirectory="PreserveNewest"
          ExcludeFromSingleFile="true" />
  </ItemGroup>
  <Target Name="ExcludeNvApiWrapperFromBundle"
          BeforeTargets="GenerateSingleFileBundle"
          DependsOnTargets="PrepareForBundle"
          Condition="'$(PublishSingleFile)' == 'true'">
    <ItemGroup>
      <FilesToBundle Remove="@(FilesToBundle)"
                     Condition="'%(FileName)%(Extension)' == 'NvAPIWrapper.dll'" />
    </ItemGroup>
  </Target>
  <Target Name="CopyReplaceableNvApiWrapper"
          AfterTargets="Publish"
          Condition="'$(PublishSingleFile)' == 'true'">
    <Copy SourceFiles="$(TargetDir)NvAPIWrapper.dll"
          DestinationFolder="$(PublishDir)" />
  </Target>
</Project>
